# version: '3'
# services:
#   app1:
#     build:
#       context: ./my-portfolio
#     ports:
#       - "5173:5173"
#     depends_on:
#       - app2
#   app2:
#     build:
#       context: ./portfolio-server
#     ports:
#       - "3000:3000"

version: '3'
services:
  app1:
    build:
      context: ./my-portfolio
    ports:
      - "5173:5173"
    networks:
      - my-network
  app2:
    build:
      context: ./portfolio-server
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
